-- MySQL Script generated by MySQL Workbench
-- 12/04/14 12:41:57
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema vvtissue
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vvtissue` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema smallbusiness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smallbusiness` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
  `Email` VARCHAR(100) NOT NULL,
  `datum` DATETIME NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;

USE `vvtissue` ;

-- -----------------------------------------------------
-- Table `vvtissue`.`Gebruiker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vvtissue`.`Gebruiker` (
  `email` VARCHAR(100) NOT NULL,
  `wachtwoord` VARCHAR(45) NOT NULL,
  `level` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vvtissue`.`Klant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vvtissue`.`Klant` (
  `klantnr` INT(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `bedrijfsnaam` VARCHAR(45) NOT NULL,
  `kvknummer` INT(11) NOT NULL,
  `btwnummer` VARCHAR(14) NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `telnummer` VARCHAR(11) BINARY NOT NULL,
  `mobnummer` VARCHAR(13) NULL DEFAULT NULL,
  `adres` VARCHAR(30) NOT NULL,
  `plaats` VARCHAR(30) NOT NULL,
  `postcode` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`klantnr`),
  UNIQUE INDEX `klantnr_UNIQUE` (`klantnr` ASC),
  UNIQUE INDEX `kvknummer_UNIQUE` (`kvknummer` ASC),
  UNIQUE INDEX `btwnummer_UNIQUE` (`btwnummer` ASC),
  INDEX `fk_Klant_Gebruiker_idx` (`email` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_Klant_Gebruiker`
    FOREIGN KEY (`email`)
    REFERENCES `vvtissue`.`Gebruiker` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vvtissue`.`Bestelling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vvtissue`.`Bestelling` (
  `bestelnr` INT(11) NOT NULL,
  `besteldatum` DATE NOT NULL,
  `bezorgdatum` DATE NOT NULL,
  `status` VARCHAR(25) NOT NULL,
  `opmerking` VARCHAR(80) NULL DEFAULT NULL,
  `klantnr` INT NOT NULL,
  PRIMARY KEY (`bestelnr`),
  UNIQUE INDEX `bestelnr_UNIQUE` (`bestelnr` ASC),
  INDEX `fk_Bestelling_Klant1_idx` (`klantnr` ASC),
  CONSTRAINT `fk_Bestelling_Klant1`
    FOREIGN KEY (`klantnr`)
    REFERENCES `vvtissue`.`Klant` (`klantnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vvtissue`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vvtissue`.`Product` (
  `productnr` INT NOT NULL AUTO_INCREMENT,
  `productnaam` VARCHAR(30) NOT NULL,
  `merk` VARCHAR(25) NOT NULL,
  `categorie` VARCHAR(25) NOT NULL,
  `omschrijving` VARCHAR(200) NOT NULL,
  `afbeelding` LONGBLOB NULL DEFAULT NULL,
  `prijs` DOUBLE NOT NULL,
  `BTW` INT NOT NULL,
  UNIQUE INDEX `productnr_UNIQUE` (`productnr` ASC),
  PRIMARY KEY (`productnr`),
  UNIQUE INDEX `productnaam_UNIQUE` (`productnaam` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vvtissue`.`Bestelregel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vvtissue`.`Bestelregel` (
  `bestelnr` INT(11) NOT NULL,
  `productnr` INT(11) NOT NULL,
  `aantal` INT(11) NOT NULL,
  `prijs` DOUBLE NOT NULL,
  PRIMARY KEY (`bestelnr`, `productnr`),
  UNIQUE INDEX `bestelnr_UNIQUE` (`bestelnr` ASC),
  UNIQUE INDEX `productnr_UNIQUE` (`productnr` ASC),
  CONSTRAINT `fk_Bestelregel_Product1`
    FOREIGN KEY (`productnr`)
    REFERENCES `vvtissue`.`Product` (`productnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bestelregel_Bestelling1`
    FOREIGN KEY (`bestelnr`)
    REFERENCES `vvtissue`.`Bestelling` (`bestelnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vvtissue`.`Voorraad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vvtissue`.`Voorraad` (
  `productnr` INT NOT NULL,
  `voorraad` INT NOT NULL,
  PRIMARY KEY (`productnr`),
  UNIQUE INDEX `productnr_UNIQUE` (`productnr` ASC),
  CONSTRAINT `fk_Voorraad_Product1`
    FOREIGN KEY (`productnr`)
    REFERENCES `vvtissue`.`Product` (`productnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vvtissue`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vvtissue`.`token` (
  `email` VARCHAR(100) NOT NULL,
  `token` TEXT NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_table1_Gebruiker1`
    FOREIGN KEY (`email`)
    REFERENCES `vvtissue`.`Gebruiker` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vvtissue`.`recovery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vvtissue`.`recovery` (
  `email` VARCHAR(100) NOT NULL,
  `datum` DATETIME NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `fk_recovery_Gebruiker1`
    FOREIGN KEY (`email`)
    REFERENCES `vvtissue`.`Gebruiker` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `smallbusiness` ;

-- -----------------------------------------------------
-- Table `smallbusiness`.`artikel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smallbusiness`.`artikel` (
  `Nummer` VARCHAR(15) NULL DEFAULT NULL,
  `Zoekkode` VARCHAR(20) NULL DEFAULT NULL,
  `Omschrijving` VARCHAR(30) NULL DEFAULT NULL,
  `Eenheid` VARCHAR(50) NULL DEFAULT NULL,
  `Leverancier` INT(11) NULL DEFAULT NULL,
  `Kiloprijs` INT(11) NULL DEFAULT NULL,
  `Inkoopprijs` DOUBLE NULL DEFAULT NULL,
  `Gewicht` INT(11) NULL DEFAULT NULL,
  `Groothandel` INT(11) NULL DEFAULT NULL,
  `Detailhandel` INT(11) NULL DEFAULT NULL,
  `Nettoprijs` DOUBLE NULL DEFAULT NULL,
  `DetailPrijs` DOUBLE NULL DEFAULT NULL,
  `Omzet` INT(11) NULL DEFAULT NULL,
  `OpslagGr` INT(11) NULL DEFAULT NULL,
  `OpslagDt` INT(11) NULL DEFAULT NULL,
  `PrijsFactor` DOUBLE NULL DEFAULT NULL,
  `Gewichtfactor` DOUBLE NULL DEFAULT NULL,
  `GeenKorting` BIT(1) NULL DEFAULT NULL,
  `Status` BIT(1) NULL DEFAULT NULL,
  `Reserve` VARCHAR(50) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smallbusiness`.`debiteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smallbusiness`.`debiteur` (
  `Nummer` INT(11) NULL DEFAULT NULL,
  `Zoekkode` VARCHAR(20) NULL DEFAULT NULL,
  `Naam` VARCHAR(30) NULL DEFAULT NULL,
  `Adres` VARCHAR(30) NULL DEFAULT NULL,
  `Postkode` VARCHAR(7) NULL DEFAULT NULL,
  `Woonplaats` VARCHAR(30) NULL DEFAULT NULL,
  `Telefoon` VARCHAR(15) NULL DEFAULT NULL,
  `Fax` VARCHAR(15) NULL DEFAULT NULL,
  `Korting` DOUBLE NULL DEFAULT NULL,
  `Groothandel` BIT(1) NULL DEFAULT NULL,
  `Omzet` INT(11) NULL DEFAULT NULL,
  `Status` BIT(1) NULL DEFAULT NULL,
  `Reserve` VARCHAR(50) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smallbusiness`.`factuur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smallbusiness`.`factuur` (
  `FactuurNummer` INT(11) NULL DEFAULT NULL,
  `FactuurDatum` DATETIME NULL DEFAULT NULL,
  `Eenheid` VARCHAR(50) NULL DEFAULT NULL,
  `Omschrijving` VARCHAR(30) NULL DEFAULT NULL,
  `DebiteurNummer` INT(11) NULL DEFAULT NULL,
  `FactuurBedrag` DOUBLE NULL DEFAULT NULL,
  `Winst` DOUBLE NULL DEFAULT NULL,
  `AantalArtikelen` INT(11) NULL DEFAULT NULL,
  `Korting` DOUBLE NULL DEFAULT NULL,
  `Status` BIT(1) NULL DEFAULT NULL,
  `Reserve` VARCHAR(50) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smallbusiness`.`factuurartikelen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smallbusiness`.`factuurartikelen` (
  `FactuurArtikelNummer` INT(11) NULL DEFAULT NULL,
  `FactuurNummer` INT(11) NULL DEFAULT NULL,
  `ArtikelNummer` VARCHAR(50) NULL DEFAULT NULL,
  `Prijs` DOUBLE NULL DEFAULT NULL,
  `Eenheid` VARCHAR(50) NULL DEFAULT NULL,
  `Aantal` DOUBLE NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smallbusiness`.`instellingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smallbusiness`.`instellingen` (
  `Nummer` INT(11) NULL DEFAULT NULL,
  `PrijsFaktorGroothandel` INT(11) NULL DEFAULT NULL,
  `PrijsFaktorDetailhandel` INT(11) NULL DEFAULT NULL,
  `GewichtFaktor` DOUBLE NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smallbusiness`.`leverancier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smallbusiness`.`leverancier` (
  `Nummer` INT(11) NULL DEFAULT NULL,
  `Naam` VARCHAR(30) NULL DEFAULT NULL,
  `Adres` VARCHAR(30) NULL DEFAULT NULL,
  `Postkode` VARCHAR(15) NULL DEFAULT NULL,
  `Woonplaats` VARCHAR(30) NULL DEFAULT NULL,
  `Telefoon` VARCHAR(15) NULL DEFAULT NULL,
  `Fax` VARCHAR(15) NULL DEFAULT NULL,
  `Bank` VARCHAR(15) NULL DEFAULT NULL,
  `BtwKode` VARCHAR(15) NULL DEFAULT NULL,
  `ValutaNummer` INT(11) NULL DEFAULT NULL,
  `GrootHOpslag` INT(11) NULL DEFAULT NULL,
  `GrootHKiloprijs` INT(11) NULL DEFAULT NULL,
  `ProjectOpslag` INT(11) NULL DEFAULT NULL,
  `ProjectKiloprijs` INT(11) NULL DEFAULT NULL,
  `Korting` INT(11) NULL DEFAULT NULL,
  `Status` BIT(1) NULL DEFAULT NULL,
  `Reserve` VARCHAR(50) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `smallbusiness`.`valuta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smallbusiness`.`valuta` (
  `Nummer` INT(11) NULL DEFAULT NULL,
  `Omschrijving` VARCHAR(30) NULL DEFAULT NULL,
  `Prijs` DOUBLE NULL DEFAULT NULL,
  `Eenheid` INT(11) NULL DEFAULT NULL,
  `Status` BIT(1) NULL DEFAULT NULL,
  `Reserve` VARCHAR(50) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
